### ISSUE TITLE
Does not work in Windows

### ISSUE THREAD

**Issue by LesterLyu** [bergos/stricter-standard#4]
Does not work when running test `npm run test` for https://github.com/rdfjs-base/data-model
```
PS D:\project\data-model> npm run test              

> @rdfjs/data-model@2.0.1 test
> stricter-standard && c8 --reporter=lcov --reporter=text mocha

stricter-standard: Unexpected linter output:

Error: Cannot read config file: D:\D:\project\data-model\node_modules\stricter-standard\eslintrc.json
Error: ENOENT: no such file or directory, open 'D:\D:\project\data-model\node_modules\stricter-standard\eslintrc.json'
    at Object.readFileSync (node:fs:453:20)
    at readFile (D:\project\data-model\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2500:35)
    at loadJSONConfigFile (D:\project\data-model\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2538:61)
    at loadConfigFile (D:\project\data-model\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2673:20)
    at ConfigArrayFactory._loadConfigData (D:\project\data-model\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2984:42)
    at ConfigArrayFactory.loadFile (D:\project\data-model\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2850:40)
    at createCLIConfigArray (D:\project\data-model\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3660:35)
    at new CascadingConfigArrayFactory (D:\project\data-model\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3735:29)
    at new CLIEngine (D:\project\data-model\node_modules\eslint\lib\cli-engine\cli-engine.js:617:36)
    at new ESLint (D:\project\data-model\node_modules\eslint\lib\eslint\eslint.js:430:27)

If you think this is a bug in `stricter-standard`, open an issue: https://github.com/rdfjs-base/data-model/issues

```

**Comment by bergos** [comment]
fixed in #5 included in release v.0.3.1
